name: "syrconnect2mqtt"
version: "1.0.0"
slug: "syrconnect2mqtt"
description: "SYR Connect â†’ MQTT Bridge for Home Assistant"
startup: services
boot: auto
init: false

arch:
  - amd64
  - armv7
  - armhf
  - aarch64
  - i386

options:
  username: ""
  password: ""
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  interval: 60

schema:
  username: str
  password: str
  mqtt_host: str
  mqtt_port: int
  interval: int
